Fix galaxy
ome/ansible-role-ice pull request #24
Opened 2023-11-01 23:30 UTC by khaledk2

I have removed the requirements from `meta/mail.yml` and put them only in the requirements.yml file as @jburel did in the docker role.
https://github.com/khaledk2/ansible-role-ice/commit/422e51460699ef3dfd7d8f6239646cd07f2f2044
This was not enough as some attributes are set during runtime and failed during the test
https://github.com/khaledk2/ansible-role-ice/actions/runs/6725911216
I have moved the role section to the `resources/playbook.yml ` as @pwalczysko  suggested during our discussion today.
This did the trick. 
It also passed the test in the GitHub actions.
https://galaxy.ansible.com/ui/standalone/roles/khaledk2/ice/
I have pushed the role to Galaxy. 
https://github.com/khaledk2/ansible-role-ice/actions/runs/6726150223

2023-11-02 10:57 UTC, khaledk2 commented
I have created a new file (`tasks/pre_tasks.yml`) and included it first in the `tasks/main.yml`  file.  This file contains the required roles and their variables using `include_role` as I think the roles section inside the `molecule/resources/playbook.yml ` is used for the `molecule `test.
It has passed the test.
I have pushed it to `Galaxy` without error.

2023-11-03 08:53 UTC, pwalczysko commented
I can confirm that with this PR, I can also push to galaxy, see https://galaxy.ansible.com/ui/standalone/roles/pwalczysko/ice/

2023-11-03 08:56 UTC, pwalczysko commented on meta/requirements.yml
> +- src: ome.basedeps
Why are basedeps twice in this list ?

2023-11-03 08:57 UTC, pwalczysko requested changes
A bit confused about the fact that basedeps are listed twice in both requirements.yml files. Nevertheless, the PR works and it fixes the Galaxy prob.

2023-11-03 11:01 UTC, pwalczysko commented
This was tested successfully in a playbook run which pointed to ``khaledk2.ice`` role in Galaxy. The role successfully installed ice on the 134...testing machine @jburel

2023-11-03 13:15 UTC, pwalczysko commented
The tests on https://github.com/ome/ansible-role-omero-server/pull/69 are passing https://github.com/ome/ansible-role-omero-server/actions/runs/6744418087 with this PR (via Galaxy khaledk2.ice)

2023-11-03 13:16 UTC, pwalczysko approved these changes

2023-11-03 14:05 UTC, merged